(defun function_from_2_to_10 (f num i)
		(cond ((and (<= num 10) (> num 0) (typep num 'integer) (<= i num))
			(print (format nil "F~D = ~F." i f))
			(setq i (+ i 1) f (* f (log i)))
			(function_from_2_to_10 f num i))
	))

(defun function_from_12_to_20 (f num j)
	(cond ((and (<= num 20) (> num 11) (typep num 'integer) (<= j num))
		(print (format nil "F~D = ~F." j f))
		(setq j (+ j 1) f (* f (sqrt j)))
		(function_from_12_to_20 f num j))
	))

(setq F1 1 F11 1 i 1 j 11)
(function_from_2_to_10 F1 2 i)
(function_from_12_to_20 F11 13 j)
