(defun function_from_2_to_10 (f i)
	(cond ((<= i 10)
		(print (format nil "F~D = ~F." i f))
		(setq i (+ i 1))
		(setq f (* f (log i)))
		(function_from_2_to_10 f i))
	))

(defun function_from_12_to_20 (f j)
	(cond ((<= j 20)
		(print (format nil "F~D = ~F." j f))
		(setq j (+ j 1))
		(setq f (* f (sqrt j)))
		(function_from_12_to_20 f j))
	))

(setq F1 1 F11 1 i 1 j 11)
(function_from_2_to_10 F1 i)
(function_from_12_to_20 F11 j)
